[phases.setup]
nixPkgs = ["python310", "postgresql"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
    "python manage.py migrate --noinput",
    "python create_admin.py"
]

[start]
cmd = "gunicorn backend.wsgi --bind 0.0.0.0:$PORT"
