# Generated by Django 5.2.7 on 2025-10-05 05:00
# Migration inicial vacía - usamos --run-syncdb para crear las tablas

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Migración vacía - las tablas se crean con --run-syncdb
    ]
